# Generated by Django 4.2.5 on 2023-10-02 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vicidApp', '0002_alter_users_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('VICID', models.CharField(max_length=8)),
                ('ACCTNO', models.CharField(max_length=10)),
                ('NO_IDEN', models.CharField(max_length=16)),
                ('NAMA_NASABAH', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='agency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Field', models.CharField(max_length=15)),
                ('Field_Awal', models.CharField(max_length=50)),
                ('Field_Update', models.CharField(max_length=50)),
                ('Record_DEL', models.CharField(max_length=1)),
                ('TGL_UPDT', models.CharField(max_length=8)),
                ('JM_UPDT', models.CharField(max_length=6)),
                ('TGL_APPRV_UPDT', models.CharField(max_length=8)),
                ('JM_APPRV_UPDT', models.CharField(max_length=6)),
                ('USR_UPDT', models.CharField(max_length=15)),
                ('APPRV_UPDT', models.CharField(max_length=15)),
                ('TGL_DELET', models.CharField(max_length=8)),
                ('JM_DELET', models.CharField(max_length=6)),
                ('TGL_APPRV_DELET', models.CharField(max_length=8)),
                ('JM_APPRV_DELET', models.CharField(max_length=6)),
                ('USR_DELET', models.CharField(max_length=15)),
                ('APPRV_DELET', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicidApp.customer')),
            ],
        ),
    ]
