# Generated by Django 4.2.5 on 2023-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicidApp', '0003_customer_users_agency_alter_users_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='VICID',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
