# Generated by Django 4.2.5 on 2023-10-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vicidApp', '0006_alter_customer_vicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vicidApp.users'),
            preserve_default=False,
        ),
    ]
