# Generated by Django 4.2.5 on 2023-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicidApp', '0007_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='APPRV_DELET',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='APPRV_UPDT',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_APPRV_DELET',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_APPRV_UPDT',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_DELET',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_UPDT',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='Record_DEL',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_APPRV_DELET',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_APPRV_UPDT',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_DELET',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_UPDT',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='USR_DELET',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='USR_UPDT',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
