# Generated by Django 4.2.5 on 2023-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicidApp', '0008_alter_history_apprv_delet_alter_history_apprv_updt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='APPRV_DELET',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='history',
            name='APPRV_UPDT',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_APPRV_DELET',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_APPRV_UPDT',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_DELET',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='history',
            name='JM_UPDT',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='history',
            name='Record_DEL',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_APPRV_DELET',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_APPRV_UPDT',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_DELET',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='TGL_UPDT',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='history',
            name='USR_DELET',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='history',
            name='USR_UPDT',
            field=models.CharField(default='', max_length=15),
        ),
    ]
